# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `devise-passwordless` gem.
# Please instead update this file by running `bin/tapioca gem devise-passwordless`.


# pkg:gem/devise-passwordless#lib/devise/passwordless/routing.rb:1
module ActionDispatch::Routing; end

# pkg:gem/devise-passwordless#lib/devise/passwordless/routing.rb:2
class ActionDispatch::Routing::Mapper
  protected

  # pkg:gem/devise-passwordless#lib/devise/passwordless/routing.rb:5
  def devise_magic_link(mapping, controllers); end
end

# Extend Devise's Helpers module to add our after_magic_link_sent_path_for
# This is defined here as a helper rather than in the sessions controller
# directly so that it can be overridden in the main ApplicationController
#
# pkg:gem/devise-passwordless#lib/devise/passwordless/version.rb:3
module Devise
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:136
  def passwordless_expire_old_tokens_on_sign_in; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:136
  def passwordless_expire_old_tokens_on_sign_in=(val); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:130
  def passwordless_login_within; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:130
  def passwordless_login_within=(val); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:133
  def passwordless_secret_key; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:133
  def passwordless_secret_key=(val); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:109
  def passwordless_tokenizer; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:109
  def passwordless_tokenizer=(val); end

  class << self
    # pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:10
    def add_module(module_name, options = T.unsafe(nil)); end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:136
    def passwordless_expire_old_tokens_on_sign_in; end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:136
    def passwordless_expire_old_tokens_on_sign_in=(val); end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:130
    def passwordless_login_within; end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:130
    def passwordless_login_within=(val); end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:133
    def passwordless_secret_key; end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:133
    def passwordless_secret_key=(val); end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:109
    def passwordless_tokenizer; end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:109
    def passwordless_tokenizer=(val); end
  end
end

# pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:68
module Devise::Controllers; end

# pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:69
module Devise::Controllers::Helpers
  mixes_in_class_methods ::Devise::Controllers::Helpers::ClassMethods

  # Method used by sessions controller to redirect user after a magic link
  # is sent from the sign in page. You can overwrite it in your
  # ApplicationController to provide a custom hook for a custom scope.
  #
  # By default it is the root_path.
  #
  # pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:75
  def after_magic_link_sent_path_for(resource_or_scope); end
end

# pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:4
class Devise::Mapping
  # pkg:gem/devise-passwordless#lib/devise/passwordless/rails.rb:6
  def magic_link_authenticatable?; end

  # pkg:gem/devise-passwordless#lib/devise/monkeypatch.rb:5
  def routes; end
end

# pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:5
module Devise::Models; end

# pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:6
module Devise::Models::MagicLinkAuthenticatable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Devise::Models::MagicLinkAuthenticatable::ClassMethods

  # Set this to false to disable magic link auth for this model instance.
  # Magic links will still be generated by the sign-in page, but visiting
  # them will instead display an error message.
  #
  # @return [Boolean]
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:57
  def active_for_magic_link_authentication?; end

  # A callback initiated after successfully authenticating. This can be
  # used to insert your own logic that is only run after the user successfully
  # authenticates.
  #
  # Example:
  #
  #   def after_magic_link_authentication
  #     self.update_attribute(:invite_code, nil)
  #   end
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:51
  def after_magic_link_authentication; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:32
  def encode_passwordless_token(*args, **kwargs); end

  # This method determines which error message to display when magic link
  # auth is disabled for this model instance.
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:63
  def magic_link_inactive_message; end

  # Not having a #password method breaks the :validatable module
  #
  # NOTE I proposed a change to Devise to fix this:
  # https://github.com/heartcombo/devise/issues/5346#issuecomment-822022834
  # As of yet it hasn't been accepted due to unknowns of the legacy code's purpose
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:27
  def password; end

  # @return [Boolean]
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:16
  def password_required?; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:36
  def send_magic_link(remember_me: T.unsafe(nil), **kwargs); end
end

# pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:69
module Devise::Models::MagicLinkAuthenticatable::ClassMethods
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:86
  def decode_passwordless_token(*args, **kwargs); end

  # We assume this method already gets the sanitized values from the
  # MagicLinkAuthenticatable strategy. If you are using this method on
  # your own, be sure to sanitize the conditions hash to only include
  # the proper fields.
  #
  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:94
  def find_for_magic_link_authentication(conditions); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_expire_old_tokens_on_sign_in; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_expire_old_tokens_on_sign_in=(value); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_login_within; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_login_within=(value); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_tokenizer; end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
  def passwordless_tokenizer=(value); end

  # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:70
  def passwordless_tokenizer_class; end

  class << self
    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
    def available_configs; end

    # pkg:gem/devise-passwordless#lib/devise/models/magic_link_authenticatable.rb:98
    def available_configs=(_arg0); end
  end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless/version.rb:4
module Devise::Passwordless
  class << self
    # pkg:gem/devise-passwordless#lib/devise/passwordless.rb:35
    def check_filter_parameters(params); end

    # pkg:gem/devise-passwordless#lib/devise/passwordless.rb:18
    def deprecator; end

    # pkg:gem/devise-passwordless#lib/devise/passwordless.rb:22
    def secret_key; end
  end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless/rails.rb:2
class Devise::Passwordless::Engine < ::Rails::Engine; end

# pkg:gem/devise-passwordless#lib/devise/passwordless.rb:16
class Devise::Passwordless::ExpiredTokenError < ::Devise::Passwordless::InvalidOrExpiredTokenError; end

# pkg:gem/devise-passwordless#lib/devise/passwordless.rb:30
Devise::Passwordless::FILTER_PARAMS_WARNING = T.let(T.unsafe(nil), String)

# pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:6
module Devise::Passwordless::Generators; end

# pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:7
class Devise::Passwordless::Generators::InstallGenerator < ::Rails::Generators::Base
  # pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:46
  def add_mailer_view; end

  # pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:14
  def update_devise_initializer; end

  # pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:60
  def update_devise_yaml; end

  private

  # https://github.com/ruby/psych/issues/322#issuecomment-328408276
  #
  # pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:104
  def force_double_quote_yaml(yaml_str); end

  class << self
    # pkg:gem/devise-passwordless#lib/generators/devise/passwordless/install_generator.rb:10
    def default_generator_root; end
  end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless.rb:12
class Devise::Passwordless::InvalidOrExpiredTokenError < ::StandardError; end

# pkg:gem/devise-passwordless#lib/devise/passwordless.rb:14
class Devise::Passwordless::InvalidTokenError < ::Devise::Passwordless::InvalidOrExpiredTokenError; end

# pkg:gem/devise-passwordless#lib/devise/passwordless/login_token.rb:2
class Devise::Passwordless::LoginToken
  class << self
    # pkg:gem/devise-passwordless#lib/devise/passwordless/login_token.rb:3
    def secret_key; end
  end
end

class Devise::Passwordless::Mailer < ::Devise::Mailer
  def magic_link(record, token, remember_me, opts = T.unsafe(nil)); end

  private

  def _layout(lookup_context, formats, keys); end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/message_encryptor_tokenizer.rb:2
class Devise::Passwordless::MessageEncryptorTokenizer
  class << self
    # @raise [InvalidTokenError]
    #
    # pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/message_encryptor_tokenizer.rb:25
    def decode(token, resource_class, as_of: T.unsafe(nil), expire_duration: T.unsafe(nil)); end

    # pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/message_encryptor_tokenizer.rb:3
    def encode(resource, extra: T.unsafe(nil), expires_at: T.unsafe(nil)); end
  end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/signed_global_id_tokenizer.rb:4
class Devise::Passwordless::SignedGlobalIDTokenizer
  class << self
    # @raise [ExpiredTokenError]
    #
    # pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/signed_global_id_tokenizer.rb:13
    def decode(token, resource_class); end

    # pkg:gem/devise-passwordless#lib/devise/passwordless/tokenizers/signed_global_id_tokenizer.rb:5
    def encode(resource, expires_in: T.unsafe(nil), expires_at: T.unsafe(nil)); end
  end
end

# pkg:gem/devise-passwordless#lib/devise/passwordless/version.rb:5
Devise::Passwordless::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:8
module Devise::Strategies; end

# pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:9
class Devise::Strategies::MagicLinkAuthenticatable < ::Devise::Strategies::Authenticatable
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:22
  def authenticate!; end

  # undef :password
  # undef :password=
  #
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:12
  def token; end

  # undef :password
  # undef :password=
  #
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:12
  def token=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:14
  def valid_for_http_auth?; end

  # @return [Boolean]
  #
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:18
  def valid_for_params_auth?; end

  private

  # Sets the authentication hash and the token from params_auth_hash or http_auth_hash.
  #
  # pkg:gem/devise-passwordless#lib/devise/strategies/magic_link_authenticatable.rb:45
  def with_authentication_hash(auth_type, auth_values); end
end
