# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `icons` gem.
# Please instead update this file by running `bin/tapioca gem icons`.


# pkg:gem/icons#lib/icons/version.rb:1
module Icons
  extend ::Icons

  # pkg:gem/icons#lib/icons/libraries.rb:18
  def libraries; end

  class << self
    # pkg:gem/icons#lib/icons.rb:19
    def config; end

    # Returns the value of attribute configuration.
    #
    # pkg:gem/icons#lib/icons.rb:12
    def configuration; end

    # Sets the attribute configuration
    #
    # @param value the value to set the attribute configuration to.
    #
    # pkg:gem/icons#lib/icons.rb:12
    def configuration=(_arg0); end

    # @yield [configuration]
    #
    # pkg:gem/icons#lib/icons.rb:14
    def configure; end
  end
end

# pkg:gem/icons#lib/icons/configuration/options.rb:4
class Icons::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # pkg:gem/icons#lib/icons/configuration.rb:11
  def initialize; end

  # pkg:gem/icons#lib/icons/configuration.rb:30
  def base_path; end

  # pkg:gem/icons#lib/icons/configuration.rb:34
  def base_path=(value); end

  # Returns the value of attribute default_library.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def default_library; end

  # Sets the attribute default_library
  #
  # @param value the value to set the attribute default_library to.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def default_library=(_arg0); end

  # Returns the value of attribute default_variant.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def default_variant; end

  # Sets the attribute default_variant
  #
  # @param value the value to set the attribute default_variant to.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def default_variant=(_arg0); end

  # pkg:gem/icons#lib/icons/configuration.rb:18
  def destination_path; end

  # pkg:gem/icons#lib/icons/configuration.rb:24
  def destination_path=(value); end

  # Returns the value of attribute icons_path.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def icons_path; end

  # Sets the attribute icons_path
  #
  # @param value the value to set the attribute icons_path to.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:8
  def icons_path=(_arg0); end

  # Returns the value of attribute libraries.
  #
  # pkg:gem/icons#lib/icons/configuration.rb:9
  def libraries; end

  private

  # pkg:gem/icons#lib/icons/configuration.rb:40
  def set_default_config; end

  # pkg:gem/icons#lib/icons/configuration.rb:46
  def set_libraries_config; end
end

# pkg:gem/icons#lib/icons/configuration/animated.rb:7
module Icons::Configuration::Animated
  extend ::Icons::Configuration::Animated

  # pkg:gem/icons#lib/icons/configuration/animated.rb:10
  def config; end

  private

  # pkg:gem/icons#lib/icons/configuration/animated.rb:18
  def default_options; end
end

# pkg:gem/icons#lib/icons/configuration/boxicons.rb:7
module Icons::Configuration::Boxicons
  extend ::Icons::Configuration::Boxicons

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:72
  def default_options; end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:21
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:67
  def setup_logos_config(options); end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:57
  def setup_regular_config(options); end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:62
  def setup_solid_config(options); end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:38
  def source; end

  # pkg:gem/icons#lib/icons/configuration/boxicons.rb:49
  def transformations; end
end

# pkg:gem/icons#lib/icons/configuration/feather.rb:7
module Icons::Configuration::Feather
  extend ::Icons::Configuration::Feather

  # pkg:gem/icons#lib/icons/configuration/feather.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/feather.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/feather.rb:31
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/feather.rb:42
  def default_options; end
end

# pkg:gem/icons#lib/icons/configuration/flags.rb:7
module Icons::Configuration::Flags
  extend ::Icons::Configuration::Flags

  # pkg:gem/icons#lib/icons/configuration/flags.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/flags.rb:20
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/flags.rb:34
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/flags.rb:63
  def default_landscape_options; end

  # pkg:gem/icons#lib/icons/configuration/flags.rb:56
  def default_square_options; end

  # pkg:gem/icons#lib/icons/configuration/flags.rb:51
  def setup_landscape_config(options); end

  # pkg:gem/icons#lib/icons/configuration/flags.rb:46
  def setup_square_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/heroicons.rb:7
module Icons::Configuration::Heroicons
  extend ::Icons::Configuration::Heroicons

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:22
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:43
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:99
  def default_micro_options; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:92
  def default_mini_options; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:77
  def default_outline_options; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:85
  def default_solid_options; end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:72
  def setup_micro_config(options); end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:67
  def setup_mini_config(options); end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:57
  def setup_outline_config(options); end

  # pkg:gem/icons#lib/icons/configuration/heroicons.rb:62
  def setup_solid_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/hugeicons.rb:7
module Icons::Configuration::Hugeicons
  extend ::Icons::Configuration::Hugeicons

  # pkg:gem/icons#lib/icons/configuration/hugeicons.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/hugeicons.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/hugeicons.rb:31
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/hugeicons.rb:42
  def default_options; end
end

# pkg:gem/icons#lib/icons/configuration/linear.rb:7
module Icons::Configuration::Linear
  extend ::Icons::Configuration::Linear

  # pkg:gem/icons#lib/icons/configuration/linear.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/linear.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/linear.rb:31
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/linear.rb:42
  def default_options; end
end

# pkg:gem/icons#lib/icons/configuration/lucide.rb:7
module Icons::Configuration::Lucide
  extend ::Icons::Configuration::Lucide

  # pkg:gem/icons#lib/icons/configuration/lucide.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/lucide.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/lucide.rb:31
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/lucide.rb:47
  def default_outline_options; end

  # pkg:gem/icons#lib/icons/configuration/lucide.rb:42
  def setup_outline_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/options.rb:5
class Icons::Configuration::Options < ::Hash
  # pkg:gem/icons#lib/icons/configuration/options.rb:6
  def method_missing(method_name, *args); end

  private

  # @return [Boolean]
  #
  # pkg:gem/icons#lib/icons/configuration/options.rb:15
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

# pkg:gem/icons#lib/icons/configuration/phosphor.rb:7
module Icons::Configuration::Phosphor
  extend ::Icons::Configuration::Phosphor

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:24
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:50
  def source; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:64
  def transformations; end

  private

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:104
  def default_bold_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:111
  def default_duotone_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:118
  def default_fill_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:125
  def default_light_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:132
  def default_regular_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:139
  def default_thin_options; end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:74
  def setup_bold_config(options); end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:79
  def setup_duotone_config(options); end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:84
  def setup_fill_config(options); end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:89
  def setup_light_config(options); end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:94
  def setup_regular_config(options); end

  # pkg:gem/icons#lib/icons/configuration/phosphor.rb:99
  def setup_thin_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/radix.rb:7
module Icons::Configuration::Radix
  extend ::Icons::Configuration::Radix

  # pkg:gem/icons#lib/icons/configuration/radix.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/radix.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/radix.rb:30
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/radix.rb:41
  def default_options; end
end

# pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:7
module Icons::Configuration::Sidekickicons
  extend ::Icons::Configuration::Sidekickicons

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:22
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:43
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:99
  def default_micro_options; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:92
  def default_mini_options; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:84
  def default_outline_options; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:77
  def default_solid_options; end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:72
  def setup_micro_config(options); end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:67
  def setup_mini_config(options); end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:57
  def setup_outline_config(options); end

  # pkg:gem/icons#lib/icons/configuration/sidekickicons.rb:62
  def setup_solid_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/tabler.rb:7
module Icons::Configuration::Tabler
  extend ::Icons::Configuration::Tabler

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:20
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:36
  def source; end

  private

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:66
  def default_filled_options; end

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:58
  def default_outline_options; end

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:53
  def setup_filled_config(options); end

  # pkg:gem/icons#lib/icons/configuration/tabler.rb:48
  def setup_outline_config(options); end
end

# pkg:gem/icons#lib/icons/configuration/weather.rb:7
module Icons::Configuration::Weather
  extend ::Icons::Configuration::Weather

  # pkg:gem/icons#lib/icons/configuration/weather.rb:10
  def config; end

  # pkg:gem/icons#lib/icons/configuration/weather.rb:19
  def initializer_config; end

  # pkg:gem/icons#lib/icons/configuration/weather.rb:30
  def source; end

  # pkg:gem/icons#lib/icons/configuration/weather.rb:39
  def transformations; end

  private

  # pkg:gem/icons#lib/icons/configuration/weather.rb:49
  def default_options; end
end

# pkg:gem/icons#lib/icons/icon/file_path.rb:6
class Icons::Icon
  # @return [Icon] a new instance of Icon
  #
  # pkg:gem/icons#lib/icons/icon.rb:9
  def initialize(name:, library:, arguments:, variant: T.unsafe(nil)); end

  # pkg:gem/icons#lib/icons/icon.rb:18
  def svg; end

  private

  # pkg:gem/icons#lib/icons/icon.rb:50
  def attach_attributes(to:); end

  # pkg:gem/icons#lib/icons/icon.rb:64
  def default(key); end

  # pkg:gem/icons#lib/icons/icon.rb:56
  def default_attributes; end

  # pkg:gem/icons#lib/icons/icon.rb:36
  def error_message; end

  # pkg:gem/icons#lib/icons/icon.rb:46
  def file_path; end

  # pkg:gem/icons#lib/icons/icon.rb:68
  def library_attributes; end

  # pkg:gem/icons#lib/icons/icon.rb:29
  def set_variant; end
end

# pkg:gem/icons#lib/icons/icon/attributes.rb:5
class Icons::Icon::Attributes
  # @return [Attributes] a new instance of Attributes
  #
  # pkg:gem/icons#lib/icons/icon/attributes.rb:6
  def initialize(default_attributes: T.unsafe(nil), arguments: T.unsafe(nil)); end

  # pkg:gem/icons#lib/icons/icon/attributes.rb:10
  def attach(to:); end

  private

  # pkg:gem/icons#lib/icons/icon/attributes.rb:24
  def class_attribute(_, value, to); end

  # pkg:gem/icons#lib/icons/icon/attributes.rb:59
  def format_attribute_name(name); end

  # pkg:gem/icons#lib/icons/icon/attributes.rb:45
  def hash_attributes(key, value, to); end

  # pkg:gem/icons#lib/icons/icon/attributes.rb:53
  def string_attributes(key, value, to); end

  # pkg:gem/icons#lib/icons/icon/attributes.rb:28
  def token_list(value); end
end

# pkg:gem/icons#lib/icons/icon/file_path.rb:7
class Icons::Icon::FilePath
  # @return [FilePath] a new instance of FilePath
  #
  # pkg:gem/icons#lib/icons/icon/file_path.rb:8
  def initialize(name:, library:, variant:); end

  # pkg:gem/icons#lib/icons/icon/file_path.rb:14
  def call; end

  private

  # pkg:gem/icons#lib/icons/icon/file_path.rb:32
  def animated_icons_path; end

  # @return [Boolean]
  #
  # pkg:gem/icons#lib/icons/icon/file_path.rb:28
  def animated_library?; end

  # pkg:gem/icons#lib/icons/icon/file_path.rb:51
  def app_path; end

  # @return [Boolean]
  #
  # pkg:gem/icons#lib/icons/icon/file_path.rb:41
  def custom_library?; end

  # pkg:gem/icons#lib/icons/icon/file_path.rb:45
  def custom_library_path; end

  # pkg:gem/icons#lib/icons/icon/file_path.rb:55
  def parts; end
end

# pkg:gem/icons#lib/icons/errors.rb:4
class Icons::IconNotFound < ::StandardError
  # @return [IconNotFound] a new instance of IconNotFound
  #
  # pkg:gem/icons#lib/icons/errors.rb:5
  def initialize(icon_name = T.unsafe(nil)); end
end

# pkg:gem/icons#lib/icons/errors.rb:14
class Icons::LibraryNotFound < ::StandardError
  # @return [LibraryNotFound] a new instance of LibraryNotFound
  #
  # pkg:gem/icons#lib/icons/errors.rb:15
  def initialize(library_name); end
end

# pkg:gem/icons#lib/icons/sync/transformations.rb:4
class Icons::Sync
  # @return [Sync] a new instance of Sync
  #
  # pkg:gem/icons#lib/icons/sync.rb:8
  def initialize(name); end

  # pkg:gem/icons#lib/icons/sync.rb:16
  def now; end

  private

  # pkg:gem/icons#lib/icons/sync.rb:38
  def clone_repository; end

  # pkg:gem/icons#lib/icons/sync.rb:58
  def move_library; end

  # pkg:gem/icons#lib/icons/sync.rb:71
  def post_error_clean_up; end

  # pkg:gem/icons#lib/icons/sync.rb:44
  def process_variants; end

  # pkg:gem/icons#lib/icons/sync.rb:67
  def purge_temp_directory; end

  # pkg:gem/icons#lib/icons/sync.rb:48
  def remove_non_svg_files; end

  # pkg:gem/icons#lib/icons/sync.rb:34
  def temp_directory_root; end
end

# pkg:gem/icons#lib/icons/sync/process_variants.rb:8
class Icons::Sync::ProcessVariants
  # @return [ProcessVariants] a new instance of ProcessVariants
  #
  # pkg:gem/icons#lib/icons/sync/process_variants.rb:9
  def initialize(temp_directory, name, library); end

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:13
  def process; end

  private

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:48
  def apply_transformations_to(destination); end

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:40
  def move_icons(source, destination); end

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:57
  def remove_files_and_folders_for(paths); end

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:63
  def remove_previously_downloaded(variants); end

  # pkg:gem/icons#lib/icons/sync/process_variants.rb:69
  def transformations; end
end

# pkg:gem/icons#lib/icons/sync/transformations.rb:5
class Icons::Sync::Transformations
  class << self
    # pkg:gem/icons#lib/icons/sync/transformations.rb:6
    def transform(filename, rules = T.unsafe(nil)); end
  end
end

# pkg:gem/icons#lib/icons/sync/transformations.rb:18
Icons::Sync::Transformations::TRANSFORMERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/icons#lib/icons/version.rb:2
Icons::VERSION = T.let(T.unsafe(nil), String)
