# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_icons` gem.
# Please instead update this file by running `bin/tapioca gem rails_icons`.


# pkg:gem/rails_icons#lib/rails_icons/version.rb:1
module RailsIcons
  class << self
    # pkg:gem/rails_icons#lib/rails_icons.rb:13
    def config; end

    # pkg:gem/rails_icons#lib/rails_icons.rb:12
    def configuration; end

    # pkg:gem/rails_icons#lib/rails_icons.rb:10
    def configure(&block); end

    # pkg:gem/rails_icons#lib/rails_icons.rb:15
    def libraries; end

    # pkg:gem/rails_icons#lib/rails_icons/engine.rb:7
    def railtie_helpers_paths; end

    # pkg:gem/rails_icons#lib/rails_icons/engine.rb:7
    def railtie_namespace; end

    # pkg:gem/rails_icons#lib/rails_icons/engine.rb:7
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/rails_icons#lib/rails_icons/engine.rb:7
    def table_name_prefix; end

    # pkg:gem/rails_icons#lib/rails_icons/engine.rb:7
    def use_relative_model_naming?; end
  end
end

# pkg:gem/rails_icons#lib/rails_icons/engine.rb:6
class RailsIcons::Engine < ::Rails::Engine; end

# pkg:gem/rails_icons#lib/rails_icons/helpers/icon_helper.rb:4
module RailsIcons::Helpers; end

# pkg:gem/rails_icons#lib/rails_icons/helpers/icon_helper.rb:5
module RailsIcons::Helpers::IconHelper
  # pkg:gem/rails_icons#lib/rails_icons/helpers/icon_helper.rb:15
  def encoded_icon(name, library: T.unsafe(nil), from: T.unsafe(nil), variant: T.unsafe(nil), **arguments); end

  # pkg:gem/rails_icons#lib/rails_icons/helpers/icon_helper.rb:6
  def icon(name, library: T.unsafe(nil), from: T.unsafe(nil), variant: T.unsafe(nil), **arguments); end
end

class RailsIcons::Preview
  include ::RailsIcons::Preview::Tags

  def icon_names(library, variant = T.unsafe(nil)); end
  def libraries; end
  def variants(library); end

  private

  def animated_gem_path; end
  def animated_icons; end
  def default_library; end
  def icons_path; end
end

module RailsIcons::Preview::Tags
  def tags(library, variant = T.unsafe(nil)); end
end

class RailsIcons::PreviewsController < ::ActionController::Base
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def library_default_variant; end
  def preview; end

  class << self
    private

    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

# pkg:gem/rails_icons#lib/rails_icons/version.rb:2
RailsIcons::VERSION = T.let(T.unsafe(nil), String)
