[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails server -b 0.0.0.0 -p $PORT -e production"
dbMigrateCommand = "bundle exec rails db:migrate"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
