# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CharacterPortraitJob`.
# Please instead update this file by running `bin/tapioca dsl CharacterPortraitJob`.


class CharacterPortraitJob
  class << self
    sig do
      params(
        character_image_id: ::Integer,
        requested_by_id: ::Integer,
        player_prompt: ::String,
        block: T.nilable(T.proc.params(job: CharacterPortraitJob).void)
      ).returns(T.any(CharacterPortraitJob, FalseClass))
    end
    def perform_later(character_image_id, requested_by_id, player_prompt, &block); end

    sig { params(character_image_id: ::Integer, requested_by_id: ::Integer, player_prompt: ::String).void }
    def perform_now(character_image_id, requested_by_id, player_prompt); end
  end
end
