# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotificationMailer`.
# Please instead update this file by running `bin/tapioca dsl NotificationMailer`.


class NotificationMailer
  class << self
    sig { params(delivery: ::NotificationMailer::Delivery).returns(::ActionMailer::MessageDelivery) }
    def new_scene(delivery); end

    sig do
      params(
        delivery: ::NotificationMailer::Delivery,
        posts: T::Array[::Post]
      ).returns(::ActionMailer::MessageDelivery)
    end
    def post_digest(delivery, posts); end

    sig { params(delivery: ::NotificationMailer::Delivery).returns(::ActionMailer::MessageDelivery) }
    def scene_resolved(delivery); end
  end
end
