# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostDigestJob`.
# Please instead update this file by running `bin/tapioca dsl PostDigestJob`.


class PostDigestJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: PostDigestJob).void)).returns(T.any(PostDigestJob, FalseClass)) }
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
