# typed: true
# frozen_string_literal: true

# Base policy generated by `rails g pundit:install`. Structure is Pundit's
# codified convention (default-deny CRUD set with new?->create? / edit?->update?
# aliases so `authorize` infers the query from action_name); we add only Sorbet.
#
# Naming convention for every policy in this app:
#
# - Capability predicates are the public surface. Controllers, views,
#   components and presenters ask only capability questions, named for the
#   game function being decided — e.g. `manage?`, `resolve?`,
#   `manage_participants?`. A capability name must survive who currently
#   satisfies it.
# - Role predicates (`gm?`, `owner?`, `write_member?`, ...) stay `private`.
#   They are the *implementation* of a capability — the one line that changes
#   when a rule granularizes (e.g. "GM-only" becoming "GM or a delegated
#   player"). Nothing outside the policy should ever ask a role question
#   directly.
# - `update?`/`destroy?`/`show?`/etc. stay, because Pundit's `authorize`
#   infers them from `action_name`, but their bodies must read as a
#   capability (delegate to a capability predicate) — they must not be
#   borrowed by callers who are asking a different question than "may this
#   action proceed."
#
# See GamePolicy#manage?, PostPolicy#participate?/#mark_read?,
# ScenePolicy#manage_participants?/#resolve?/#join?,
# CharacterPolicy#assign_owner?, and NotebookEntryPolicy#manage? for the
# worked examples.
class ApplicationPolicy
  extend T::Sig

  attr_reader :user, :record

  sig { params(user: T.untyped, record: T.untyped).void }
  def initialize(user, record)
    @user = user
    @record = record
  end

  sig { returns(T::Boolean) }
  def index?
    false
  end

  sig { returns(T::Boolean) }
  def show?
    false
  end

  sig { returns(T::Boolean) }
  def create?
    false
  end

  sig { returns(T::Boolean) }
  def new?
    create?
  end

  sig { returns(T::Boolean) }
  def update?
    false
  end

  sig { returns(T::Boolean) }
  def edit?
    update?
  end

  sig { returns(T::Boolean) }
  def destroy?
    false
  end

  class Scope
    extend T::Sig

    sig { params(user: T.untyped, scope: T.untyped).void }
    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    sig { returns(T.untyped) }
    def resolve
      raise NoMethodError, "You must define #resolve in #{self.class}"
    end

    private

    attr_reader :user, :scope
  end
end
