# typed: true
# frozen_string_literal: true

# Base policy generated by `rails g pundit:install`. Structure is Pundit's
# codified convention (default-deny CRUD set with new?->create? / edit?->update?
# aliases so `authorize` infers the query from action_name); we add only Sorbet.
class ApplicationPolicy
  extend T::Sig

  attr_reader :user, :record

  sig { params(user: T.untyped, record: T.untyped).void }
  def initialize(user, record)
    @user = user
    @record = record
  end

  sig { returns(T::Boolean) }
  def index?
    false
  end

  sig { returns(T::Boolean) }
  def show?
    false
  end

  sig { returns(T::Boolean) }
  def create?
    false
  end

  sig { returns(T::Boolean) }
  def new?
    create?
  end

  sig { returns(T::Boolean) }
  def update?
    false
  end

  sig { returns(T::Boolean) }
  def edit?
    update?
  end

  sig { returns(T::Boolean) }
  def destroy?
    false
  end

  class Scope
    extend T::Sig

    sig { params(user: T.untyped, scope: T.untyped).void }
    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    sig { returns(T.untyped) }
    def resolve
      raise NoMethodError, "You must define #resolve in #{self.class}"
    end

    private

    attr_reader :user, :scope
  end
end
