default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: <%= ENV["DATABASE_URL"] ? "postgresql" : "sqlite3" %>
  <% if ENV["DATABASE_URL"] %>
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  <% else %>
  database: storage/test.sqlite3
  <% end %>

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *primary_production
    database: play_by_post_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: play_by_post_production_queue
    migrations_paths: db/queue_migrate
