require "rails_helper"

RSpec.describe Shared::SceneSummaryFormComponent, type: :component do
  let(:game) { build_stubbed(:game) }
  let(:scene) { build_stubbed(:scene, game: game) }
  let(:urls) { double("urls", game_scene_scene_summary_path: "/summary") }
  let(:policy) { instance_double(SceneSummaryPolicy, manage?: true) }

  def presenter_for(summary)
    SceneSummaryPresenter.new(summary, game: game, urls: urls, policy: policy)
  end

  context "when creating a new summary" do
    let(:summary) { SceneSummary.new(scene: scene) }

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "editing? returns false" do
      expect(component.editing?).to be(false)
    end

    it "heading returns 'Write Scene Summary'" do
      expect(component.heading).to eq("Write Scene Summary")
    end

    it "submit_label returns 'Save Summary'" do
      expect(component.submit_label).to eq("Save Summary")
    end

    it "form_id returns the new-form id" do
      expect(component.form_id).to eq("scene_summary_new_form")
    end

    it "show_ai_notice? returns false" do
      expect(component.show_ai_notice?).to be(false)
    end

    it "renders no error block when there are no errors" do
      render_inline(component)
      expect(page).to have_no_css(".text-danger")
    end

    it "renders a form with the new-form id" do
      render_inline(component)
      expect(page).to have_css("form#scene_summary_new_form")
    end

    it "does not render the AI notice" do
      render_inline(component)
      expect(page).not_to have_text("generated by AI")
    end
  end

  context "when editing an existing summary" do
    let(:summary) { build_stubbed(:scene_summary, scene: scene) }

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "editing? returns true" do
      expect(component.editing?).to be(true)
    end

    it "heading returns 'Edit Scene Summary'" do
      expect(component.heading).to eq("Edit Scene Summary")
    end

    it "submit_label returns 'Update Summary'" do
      expect(component.submit_label).to eq("Update Summary")
    end

    it "form_id returns the edit-form id" do
      expect(component.form_id).to eq("scene_summary_edit_form")
    end

    it "renders a form with the edit-form id" do
      render_inline(component)
      expect(page).to have_css("form#scene_summary_edit_form")
    end
  end

  context "when editing an AI-generated summary" do
    let(:summary) { build_stubbed(:scene_summary, :ai_generated, scene: scene) }

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "show_ai_notice? returns true" do
      expect(component.show_ai_notice?).to be(true)
    end

    it "renders the AI notice" do
      render_inline(component)
      expect(page).to have_text("generated by AI")
    end
  end

  context "when editing a non-AI-generated summary" do
    let(:summary) { build_stubbed(:scene_summary, generated_at: nil, scene: scene) }

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "show_ai_notice? returns false" do
      expect(component.show_ai_notice?).to be(false)
    end
  end

  context "when not editing but generated_at is present" do
    let(:summary) { SceneSummary.new(scene: scene, generated_at: Time.current) }

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "show_ai_notice? returns false because not editing" do
      expect(component.show_ai_notice?).to be(false)
    end
  end

  context "when the summary has validation errors" do
    let(:summary) do
      s = SceneSummary.new(scene: scene)
      s.errors.add(:body, "can't be blank")
      s
    end

    subject(:component) { described_class.new(summary: presenter_for(summary)) }

    it "renders the error block when there are errors" do
      render_inline(component)
      expect(page).to have_css(".text-danger", text: "Body can't be blank")
    end

    it "error_messages returns the messages" do
      expect(component.error_messages).to include("Body can't be blank")
    end

    it "renders the error message" do
      render_inline(component)
      expect(page).to have_text("Body can't be blank")
    end
  end
end
