require "rails_helper"

RSpec.describe Shared::SceneSummaryFormComponent, type: :component do
  let(:game) { build_stubbed(:game) }
  let(:scene) { build_stubbed(:scene, game: game) }

  context "when creating a new summary" do
    let(:summary) { SceneSummary.new }

    subject(:component) { described_class.new(game: game, scene: scene, summary: summary) }

    it "editing? returns false" do
      expect(component.editing?).to be(false)
    end

    it "heading returns 'Write Scene Summary'" do
      expect(component.heading).to eq("Write Scene Summary")
    end

    it "submit_label returns 'Save Summary'" do
      expect(component.submit_label).to eq("Save Summary")
    end

    it "show_ai_notice? returns false" do
      expect(component.show_ai_notice?).to be(false)
    end

    it "has_errors? returns false when no errors" do
      expect(component.has_errors?).to be(false)
    end

    it "renders the heading" do
      render_inline(component)
      expect(page).to have_text("Write Scene Summary")
    end

    it "renders a Save Summary button" do
      render_inline(component)
      expect(page).to have_button("Save Summary")
    end

    it "does not render the AI notice" do
      render_inline(component)
      expect(page).not_to have_text("generated by AI")
    end
  end

  context "when editing an existing summary" do
    let(:summary) { build_stubbed(:scene_summary, scene: scene) }

    subject(:component) { described_class.new(game: game, scene: scene, summary: summary) }

    it "editing? returns true" do
      expect(component.editing?).to be(true)
    end

    it "heading returns 'Edit Scene Summary'" do
      expect(component.heading).to eq("Edit Scene Summary")
    end

    it "submit_label returns 'Update Summary'" do
      expect(component.submit_label).to eq("Update Summary")
    end

    it "renders the Update Summary button" do
      render_inline(component)
      expect(page).to have_button("Update Summary")
    end
  end

  context "when editing an AI-generated summary" do
    let(:summary) { build_stubbed(:scene_summary, :ai_generated, scene: scene) }

    subject(:component) { described_class.new(game: game, scene: scene, summary: summary) }

    it "show_ai_notice? returns true" do
      expect(component.show_ai_notice?).to be(true)
    end

    it "renders the AI notice" do
      render_inline(component)
      expect(page).to have_text("generated by AI")
    end
  end

  context "when the summary has validation errors" do
    let(:summary) do
      s = SceneSummary.new
      s.errors.add(:body, "can't be blank")
      s
    end

    subject(:component) { described_class.new(game: game, scene: scene, summary: summary) }

    it "has_errors? returns true" do
      expect(component.has_errors?).to be(true)
    end

    it "error_count returns the error count" do
      expect(component.error_count).to eq(1)
    end

    it "error_messages returns the messages" do
      expect(component.error_messages).to include("Body can't be blank")
    end

    it "renders the error message" do
      render_inline(component)
      expect(page).to have_text("Body can't be blank")
    end
  end
end
