require "rails_helper"

# CharacterPortraitGeneration fills in a pending skeleton CharacterImage:
# compose -> moderate -> generate -> complete the skeleton, or fail it. The AI
# collaborators (Ai::Moderation, Ai::Funding) are stubbed so the pipeline is
# tested without HTTP or a live pool.
RSpec.describe CharacterPortraitGeneration do
  let!(:game) { create(:game) }
  let!(:player) { create(:user, :with_profile) }
  let!(:payer) { create(:user, :with_profile) }
  let!(:character) { create(:character, game: game, user: player) }
  # A pending skeleton: no file attached, not failed.
  let!(:image) { character.character_images.create! }

  let(:image_result) { Ai::ImageRequest::Result.new(png_bytes: "\x89PNG bytes".b, cost: 0.02) }
  let(:spend) { Ai::Funding::Spend.new(value: image_result, funded_by: payer) }

  def run
    described_class.new(image, player.id, "a grizzled dwarven smith").run
  end

  # The moderation OpenAI key lives in encrypted credentials (credentials.openai.api_key);
  # stub it for every example so building Ai::Moderation doesn't hit real creds.
  before { allow(Rails.application.credentials).to receive(:openai).and_return(double(api_key: "openai-test-key")) }

  def stub_moderation(flagged:, reasons: [])
    verdict = Ai::Moderation::Verdict.new(flagged: flagged, reasons: reasons)
    allow(Ai::Moderation).to receive(:new).and_return(instance_double(Ai::Moderation, call: verdict))
  end

  def stub_funding(raises: nil)
    funding = instance_double(Ai::Funding)
    if raises
      allow(funding).to receive(:call).and_raise(raises)
    else
      allow(funding).to receive(:call).and_return(spend)
    end
    allow(Ai::Funding).to receive(:new).and_return(funding)
  end

  context "when the prompt passes moderation and generation succeeds" do
    before do
      stub_moderation(flagged: false)
      stub_funding
    end

    it "completes the skeleton: attaches the generated bytes and stamps provenance" do
      run
      image.reload

      expect(image.file).to be_attached
      expect(image.file.download).to eq(image_result.png_bytes)
      expect(image.ai_generated?).to be(true)
      expect(image.pending?).to be(false)
    end

    it "does NOT make the generated image current (no auto-publish)" do
      run
      expect(image.reload.current).to be(false)
    end

    it "writes an AiGeneration audit row attributing requester and pooled payer" do
      expect { run }.to change(AiGeneration, :count).by(1)

      row = AiGeneration.last
      expect(row).to have_attributes(
        feature: "character_portrait", model_used: "test/image-model",
        requested_by_id: player.id, funded_by_id: payer.id,
        asset_type: "CharacterImage", asset_id: image.id, cost: 0.02
      )
    end

    it "does not mark the skeleton failed" do
      run
      expect(image.reload.failed?).to be(false)
    end
  end

  context "when moderation flags the prompt" do
    before { stub_moderation(flagged: true, reasons: [ "flagged by moderation: sexual" ]) }

    it "fails the skeleton before spending a key (no funding, no image, no audit row)" do
      expect(Ai::Funding).not_to receive(:new)

      expect { run }.to change(AiGeneration, :count).by(0)
      expect(image.reload.file).not_to be_attached
    end

    it "records a player-facing moderation failure reason" do
      run
      expect(image.reload).to be_failed
      expect(image.failure_reason).to match(/blocked by content moderation/)
    end

    it "logs the block with the flagged categories and both prompt parts for the operator" do
      expect(Rails.logger).to receive(:warn)
        .with(/blocked.*flagged by moderation: sexual.*player_prompt/m)

      run
    end
  end

  context "when generation is refused by the image model" do
    before do
      stub_moderation(flagged: false)
      stub_funding(raises: Ai::ImageRequest::Refused.new("policy"))
    end

    it "fails the skeleton with a generic failure reason, no audit row" do
      expect { run }.to change(AiGeneration, :count).by(0)

      expect(image.reload).to be_failed
      expect(image.failure_reason).to match(/could not be generated/)
    end

    it "logs the failure with the character id and underlying error for the operator" do
      expect(Rails.logger).to receive(:error).with(/failed character=#{image.character_id}: policy/)

      run
    end
  end

  context "when the game pool has no working key" do
    before do
      stub_moderation(flagged: false)
      stub_funding(raises: Ai::Funding::Exhausted.new("no key"))
    end

    it "fails the skeleton, no audit row" do
      expect { run }.to change(AiGeneration, :count).by(0)
      expect(image.reload).to be_failed
    end
  end

  # An integration pass that exercises the REAL collaborators — the moderation
  # HTTP and the image HTTP are stubbed at their boundaries, but Ai::Moderation,
  # Ai::Funding, the resolver, and the app-key wiring all run for real, so the
  # pipeline's construction (not just its happy-path outcome) is covered.
  context "end-to-end with real funding and a real (stubbed-HTTP) image request" do
    before do
      json = { "Content-Type" => "application/json" }
      # Real moderation: an unflagged omni-moderation result, HTTP stubbed.
      moderation_stubs = "Faraday::Adapter::Test::Stubs".constantize.new
      moderation_stubs.post("https://api.openai.com/v1/moderations") do |_env|
        [ 200, json, JSON.generate("results" => [ { "flagged" => false, "categories" => {}, "category_scores" => {} } ]) ]
      end
      allow(Ai::Moderation).to receive(:new).and_wrap_original do |orig, **kwargs|
        orig.call(**kwargs.merge(adapter: [ :test, moderation_stubs ]))
      end

      # Real pool: one authorized payer with a present key.
      allow_any_instance_of(User).to receive(:ai_key_present?).and_return(true)
      create(:game_key_authorization, game: game, user: payer, feature: "character_portrait")
      allow_any_instance_of(Crypto::StoredKeySource).to receive(:for_user).and_return("key-abc")

      # Real image request through Ai::Funding, HTTP stubbed to a success.
      allow(Ai::ImageRequest).to receive(:new).and_wrap_original do |orig, **kwargs|
        image_stubs = "Faraday::Adapter::Test::Stubs".constantize.new
        image_stubs.post("https://openrouter.ai/api/v1/images") do |_env|
          [ 200, json, JSON.generate("data" => [ { "b64_json" => Base64.strict_encode64("PNG-BYTES") } ], "usage" => { "cost" => 0.05 }) ]
        end
        orig.call(**kwargs.merge(adapter: [ :test, image_stubs ]))
      end
    end

    it "completes the skeleton and audits the real pooled payer" do
      run
      image.reload

      expect(image.file.download).to eq("PNG-BYTES")
      expect(AiGeneration.last).to have_attributes(funded_by_id: payer.id, cost: 0.05)
    end
  end
end
