# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

class Devise::Passwordless::SessionsController < ::DeviseController; end
module ERB::Escape; end
module Set::SubclassCompatible; end
module Set::SubclassCompatible::ClassMethods; end
