# typed: true

class User < ApplicationRecord
  extend T::Sig

  devise :magic_link_authenticatable, :rememberable

  has_one :user_profile, dependent: :destroy
  has_many :game_members, dependent: :destroy
  has_many :games, through: :game_members
  has_many :scene_participants, dependent: :destroy
  has_many :scenes, through: :scene_participants
  has_many :posts, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :feedback, dependent: :destroy
  has_many :api_tokens, dependent: :destroy
  has_many :user_images, dependent: :destroy

  # Every user needs a stable secret so the passwordless model has a real
  # authenticatable_salt (see #authenticatable_salt): assign it on create,
  # in-band and visible here rather than behind a before_create callback
  # (bin/check-callbacks). save and save! are both overridden because create
  # routes through save and create! through save!; a token cleared later is
  # regenerated by #after_magic_link_authentication, not here.
  sig { params(options: T.untyped).returns(T.untyped) }
  def save(**options)
    ensure_remember_token if new_record?
    super
  end

  sig { params(options: T.untyped).returns(T.untyped) }
  def save!(**options)
    ensure_remember_token if new_record?
    super
  end

  sig { returns(T.nilable(String)) }
  def display_name
    user_profile&.display_name
  end

  # The library image currently serving as this user's avatar, or nil when the
  # library is empty / none is marked current.
  sig { returns(T.nilable(UserImage)) }
  def current_avatar
    user_images.current.first
  end

  # The display variant of the current avatar, or nil when there is none — the
  # profile screen's avatar <img>.
  sig { returns(T.untyped) }
  def avatar_variant
    current_avatar&.display_variant
  end

  # Deliver Devise mail (the passwordless magic link) through Active Job /
  # Solid Queue so it is sent by the worker, matching every other mailer in the
  # app (NotificationMailer, ExportMailer, InvitationMailer all use
  # deliver_later). Devise's default sends the magic link with deliver_now,
  # inline in the web request — the only email that bypassed the worker.
  sig { params(notification: Symbol, args: T.untyped).void }
  def send_devise_notification(notification, *args)
    message = T.unsafe(self).devise_mailer.send(notification, self, *args)
    deliver_off_request_cycle(message)
  end

  # Passwordless users have no encrypted_password, so Devise's default
  # authenticatable_salt is nil — which makes session validation a permanent
  # no-op (`nil == nil`) and makes `:rememberable` raise. Anchoring the salt to
  # remember_token gives sessions a real, per-user secret: rotating the token
  # invalidates that user's sessions and remember-me cookie.
  sig { returns(T.nilable(String)) }
  def authenticatable_salt
    remember_token
  end

  # Runs during magic-link authentication, before the session is serialized. A
  # prior sign-out clears remember_token (expire_all_remember_me_on_sign_out), so
  # regenerate it here to guarantee the salt is present for the new session.
  sig { void }
  def after_magic_link_authentication
    update_column(:remember_token, Devise.friendly_token) if remember_token.blank?
  end

  private

  sig { void }
  def ensure_remember_token
    self.remember_token ||= Devise.friendly_token
  end

  # Devise's default delivery is deliver_now; queue it onto Active Job when the
  # mailer hands back an ActionMailer::MessageDelivery (every mailer in the app
  # except the raw Mail::Message some Devise notifications hand back),
  # otherwise send inline. Dispatched on class, not respond_to?(:deliver_later).
  sig { params(message: T.untyped).void }
  def deliver_off_request_cycle(message)
    case message
    when ActionMailer::MessageDelivery
      message.deliver_later
    else
      message.deliver_now
    end
  end
end
